version: "3.9"

services:
  backend:
    image: vianneygln/league-infos-app-backend:latest
    container_name: spring-app
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      API_KEY_RIOT: ${API_KEY_RIOT}
      API_KEY_LEAGUE_INFO: ${API_KEY_LEAGUE_INFO}
      API_KEY_OPEN_AI: ${API_KEY_OPEN_AI}
    ports:
      - "8080:8080"
    restart: always

  frontend:
    image: vianneygln/league-infos-app-frontend:latest
    container_name: angular-app
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always